controller_list:
  - name: arm_controller
    action_ns: ""
    type: FollowJointTrajectory
    default: true
    joints:
      - torso_turn
      - torso_lift
      - shoulder
      - elbow
      - wrist
  - name: gripper_controller
    action_ns: ""
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper
  - name: head_controller
    action_ns: ""
    type: FollowJointTrajectory
    default: true
    joints:
      - head_pan
      - head_tilt