sensors: 
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /korus/sensor_3d/depth_registered/points
    filtered_cloud_topic: filtered_cloud
    max_range: 2.0
    frame_subsample: 1
    point_subsample: 1
    shape_padding: 0.10
    shape_scale: 1.1
    self_mask:
      min_sensor_dist: .5
      self_see_default_padding: .04
      self_see_default_scale: 1.0
      self_see_links:
       - name: base_link
       - name: shoulder_link
       - name: upper_arm_link
       - name: lower_arm_link
       - name: wrist_link
       - name: palm_link
       - name: finger_left_knuckle_1
       - name: finger_left_knuckle_2
       - name: finger_right_knuckle_1
       - name: finger_right_knuckle_2