sensors: 
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /korus/sensor_3d/depth_registered/points
    filtered_cloud_topic: filtered_cloud
    max_range: 5.0
    frame_subsample: 1
    point_subsample: 1
    shape_padding: 0.01
    shape_scale: 1.0
    self_mask:
      min_sensor_dist: .8
      self_see_default_padding: .04
      self_see_default_scale: 1.0
      self_see_links:
       - name: base_link