#!/usr/bin/env python

import roslib; roslib.load_manifest('korus_meta')
import rospy
from actionlib_msgs.msg import GoalStatusArray
from actionlib_msgs.msg import GoalID

received_id = False
goal_id = GoalID()

def goalStatus(status):
    global received_id
    global goal_id
    if ( not received_id ):
        rospy.loginfo("Goal id: %s",status.status_list[0].goal_id.id)
        goal_id.id = status.status_list[0].goal_id.id
    received_id = True

def main():
    global id
    rospy.init_node('cancel_move_base_goal', anonymous=True)
    pub = rospy.Publisher('/korus/move_base/cancel', GoalID)
    sub = rospy.Subscriber("/korus/move_base/status", GoalStatusArray, goalStatus)
    rospy.loginfo("Retrieving goal id...")
    while not received_id:
        rospy.loginfo("...")
        rospy.sleep(1)
    sub.unregister()
    goal_id.stamp = rospy.get_rostime()
    rospy.loginfo("Cancelling goal...")
    pub.publish(goal_id)
    rospy.sleep(1)

if __name__ == '__main__':
    main()