#!/bin/bash

# Save map to file
# The map name must be provided with MAP_NAME environment variable or -m argument
# The map topic can also be provided with environment variable MAP_TOPIC or -t argument;
# if not, the default value is used (/$ROBOT_NAME/map)

ROBOT_NAME=korus

function usage()
{
  echo "usage: save_map -m <map name> [ -t <map topic> ] | [ -h ]"
}

# parse command line
while [ "$1" != "" ]; do
  case $1 in
    -m | --map )    shift
                    MAP_NAME=$1
                    ;;
    -t | --topic )  shift
                    MAP_TOPIC=$1
                    ;;
    -h | --help )   usage
                    exit
                    ;;
     * )            usage
                    exit 1
  esac
  shift
done

# check MAP_TOPIC; it isn't mandatory
if [ -z "$MAP_TOPIC" ]; then
  MAP_TOPIC="/$ROBOT_NAME/map"
  echo "Reading from default topic $MAP_TOPIC
else
  echo "Reading from topic $MAP_TOPIC
fi

# check MAP_NAME; it's mandatory
if [ -z "$MAP_NAME" ]; then
  echo "ERROR: map name not provided"
  usage
  exit 1
fi

rosrun map_server map_saver -f $MAP_NAME map:=$MAP_TOPIC
